.\" For information on how to format me, see
.\"     https://www.gnu.org/software/groff/manual/html_node/Man-usage.html
.\"     http://www.tldp.org/HOWTO/Man-Page/q3.html
.\"     http://babbage.cs.qc.edu/courses/cs701/Handouts/man_pages.html
.\"     http://www.schweikhardt.net/man_page_howto.html

.TH emo 7 2015-2-27 "Revision 0.1" "The Emoticon Guide"

.SH
DESCRIPTION

.P
This is a collection of emoticons and emoji commonly used in text-based
communication, particularly via e-mail or IRC. Particular care is taken to
include all common connotations of emoticons, to help the reader decipher
complicated or ambiguous emotions.

.SH
INSTALLATION

.P
On UNIX systems, this document can be installed so that it is accessible with
man(1):

.RS
$ cd emo/

$ export MANDIR="..." # defaults to /usr/share/man/

$ sudo make -e install

$ sudo make -e uninstall
.RE

.P
It can then be accessed with the traditional

.RS
$ man emo
.RE

.SH
HOW TO USE THIS MANUAL

.P
This manual is meant to be used in one of two ways: forward-searching for the
definition of an emoticon and reverse-searching for an appropriate emoticon for
some context. Either search can be performed manually by perusing the list, or
by using your pager's search feature (for example, less(1) lets you search with
the `/` character).

.P
Many emoticons may be rewritten using three characters by placing a hyphen (-)
character between the eyes and mouth to represent a nose. By convention, this
reference does not include the nosed versions of such emoticons. (Emoticons
where the nose is mandatory are, of course, listed as such).

.P
Some smileys are reversible due to the symmetry of the constituent characters.
In such cases, the most commonly-used orientation (generally eyes-first) is
used.

.SH
THE LIST

.IP :)
Perhaps the most basic emoticon listed. Conveys happiness, contentment,
gratitude, etc.

.IP ":( or :'("
Conveys sadness, disappointment, and misery.

.IP ;)
Like a wink. Indicates that some positive information was left unsaid, but that
based on context the reader should be able to derive this information.

.IP :P
Indicates that the preceding remark was humerous, sarcastic, or otherwise
lighthearted and not meant to be taken seriously.

.IP :D
Conveys gladness, extreme joy, sudden excitement, etc.

.IP D:
Conveys sudden disappointment, sadness, devastation, etc.

.IP :/
Conveys uncertainty about a situation. Indicates doubt or confusion.

.IP ":O or :o"
Conveys surprise, but not necessarily a positive or negative reaction.

.IP "B) or BD"
Indicates that the speaker feels a certain degree of "coolness" after
having said the preceding remark.

.IP XD
Conveys that the speaker found a recent remark extremely amusing.

.IP :3
The `kitty face'. Conveys a cat-like feeling of happiness.

.IP c:
Conveys a heightened sense of happiness, joy, etc.

.IP :c
Conveys a heightened sense of sadness, sudden disappointment, etc.

.IP :|
Conveys indifference or mild annoyance.

.IP :<
Conveys anger or moderate annoyance.

.IP :x
Conveys nervousness or slight embarrassment at something said.

.IP ">:) or >:D or >:3"
Conveys a sense of devious happiness or `evil laughter'.

.IP >:|
Conveys moderately high annoyance.

.IP >:(
Conveys anger, disappointment, resent, fury.

.IP <3
A heart. Conveys love or deep appreciation.

.IP "o/ or \\\\o"
A person waving. Used as a greeting.

.IP "\\\\o/"
A person with both hands up. Used in a celebratory manner.

.IP "^^ or ^.^ or ^_^ or ^-^"
Conveys happiness or contentedness.

.IP "=^.^= or =^_^= or =^-^="
Like a variation of the `kitty face'. Also conveys happiness and contentedness.

.IP "-.- or -_-"
Conveys indifference or annoyance.

.IP "O_o or O.o or 0.o or o_0"
Conveys surprise or astonishment. Any combination of zero (0), capital O (O),
and lowercase O (o), and either a dot (.) or an underscore (_) are acceptable.

.IP ">< or >.< or >_<"
Conveys distress or frustration.

.SH
NOTE ON PARENTHESES

.P
The usage of parenthesis-terminated emoticons within parenthesized statements
merits some discussion.  There are several possible conventions which can be
used.

We can optimize for grammatical correctness by placing an additional closing
parenthesis after the emoticon:

.RS
(I like it the way it is. :))
.RE

However, this looks awkward to many. The alternative is to leave off the
trailing parenthesis:

.RS
(I like it the way it is. :)
.RE

This, however, appears incomplete and is not strictly correct. A compromise can
be achieved by placing a space between the two parentheses:

.RS
(I like it the way it is. :) )
.RE

In general, it is left to the writer to choose a style which they prefer.

.P
See also: <http://xkcd.com/541/>

.SH
AUTHORS

.P
hardmath123, Tamini, rtmiu

.SH
LICENSE

.P
This list is Unlicensed. You should have received a copy of the Unlicense with
this file. If not, you can obtain it for free at <http://unlicense.org>.

.SH
CONTRIBUTING

.P
Contributions are welcome, as long as they are well-intentioned, sufficiently
accurate, and suitably notable. Please submit pull requests to the git
repository containing the original groff source. If there are many commits in
your PR, please recompile README.txt at most once, preferably at the end in a
separate commit with an appropriate message.

You can find instructions on how to build this file in the Makefile bundled
with the source. A comment at the top of the source provides resources for
working with groff(1), however, you should be able to figure out what's going
on yourself.

.SH
SEE ALSO

<http://urbandictionary.com>
